// src/app/mini-map/mini-map.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Polity } from '../polity/polity';
import { TileComponent } from '../tile/tile.component';
import { Region } from '../region/region';
import { tropical, dry, temperate, continental, polar, ocean } from '../region/climate';
import { NoPolity } from '../polity/noPolity';
import { Band } from '../polity/band';
import { River, euphrates, tigris, jordan } from '../region/river';
import { Village } from '../polity/village';

@Component({
  selector: 'app-mini-map',
  templateUrl: './mini-map.component.html',
  styleUrls: ['./mini-map.component.scss']
})
export class MiniMapComponent implements OnInit {
  public year = 0;
  @Input() title:string;
  @Input() regions: Region[];
  @Input() rivers:River[];


  public polities:Polity[] = [];


  public selectedPolity: Polity = new Polity();

  public interval;

  


  constructor() {
  }


  ngOnInit() {
    // ADD POLITIES
    this.polities.push(new Band(this.regions[65], 'Origin', 10, true));
    this.regions[65]._polity = this.polities[0];


    // this.selectedPolity = this.polities[0];
    // this.selectedPolity._selected = 'selected';
    
    //ADD RIVERS
    this.rivers.forEach((river) => {
      this.drawRivers(river.riverDrawing());
      //MUST CONSOLIDATE YIELDS FROM DIFFERENT RIVERS
      let riverYields = river.tileYields();
      this.regions.forEach((region) => {
        if(riverYields[`${region._col}-${region._row}`] !== undefined){
          region._riverConnections += riverYields[`${region._col}-${region._row}`];
          // console.log(region.id + " has " + region._riverConnections + " connections!");
        }
      })
      // console.log(river.tileYields());
    })

  }

  recievePolity($event) {
    this.regions.forEach((region) => {
      if(region._polity !== $event){region._polity._selected = 'not-selected';}
    })
    this.selectedPolity = $event;
  }

  getRegionById(id){
    //creating a fake deault region return probably BAD idea...
    let returnedRegion:Region = new Region(0,0, continental, new NoPolity());
    this.regions.forEach((region) => { 
      if(region.id === id){returnedRegion = region;}
    })
    return returnedRegion;
  }

  forwardYears(number) {
    let intNumber = parseInt(number);
    // 1. UPDATE YEAR
    this.year += intNumber;
    for (let i = 0; i < intNumber; i++) {
      // 2. POLITIES ACT
      this.polities.forEach((polity) => { 
        polity.act(this.regions); 
      })
      // 3. REGIONS ACT
      this.regions.forEach((region) => { 
        // ADD NEW REGIONS TO MAIN ARRAY
        if(!region._polity._partOfMainArray && region._polity.polityType !== 'None'){
          this.polities.push(region._polity)
          region._polity._partOfMainArray = true;
        }
        region.replenishFood(); 
      })
      // 4. REMOVE DEAD POLITIES
      this.polities.forEach((polity,index) => {
        //remove any polities without any people
        if(polity._population <= 1 && polity !== undefined && polity.polityType !== 'None'){
          polity._region._polity = new NoPolity();
          this.polities.splice(index,1);
        }
       })

      // 4. RESET POLITY MOVEMENT BOOLEANS ?? DON'T THINK I NEED THIS NOW THAT THEY ARE SEPARATE FROM REGIONS
      //this.polities.forEach((polity) => { polity._hasMoved = false; })
    }
  }

  play(number){
    // this.forwardYears(1);
    let intNumber = parseInt(number);
    this.pause();
    this.interval = setInterval(()=> {
      this.forwardYears(intNumber); },1000); 
  }

  pause(){
    clearInterval(this.interval);
  }

  reset(){
    this.polities = [];
    this.regions.forEach((region) => {
      region._polity = new NoPolity();
    })
    this.year = 0;
    this.ngOnInit();
  }


  globalPopulation(){
    let globalPopulation = 0;
    this.polities.forEach((polity) => {
      globalPopulation += polity._population;
    })
    return globalPopulation;
  }
  globalFoodYielded(){
    let globalFood = 0;
    this.regions.forEach((region) => { 
      globalFood += region._foodYield;
    })
    return globalFood;
  }
  globalFoodStored(){
    let globalFoodStored = 0;
    this.polities.forEach((polity) => {
      globalFoodStored += polity._foodStored;
    })
    return globalFoodStored;
  }

  drawRivers(riverLines){
    this.regions.forEach((region) => {
      if(riverLines[`${region._col}-${region._row}`] !== undefined){
        for(let i=0; i < riverLines[`${region._col}-${region._row}`].length; i++){
          region._borders[i] = riverLines[`${region._col}-${region._row}`][i];
         }
      }
    })
  }
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<div class="map-container">
    <div class="title-data-container">
        <div class="map-title">{{title}}</div>

    </div>

    <div class="tile-container">
        <app-tile (selectedPolity)="recievePolity($event)" *ngFor="let region of regions" [_region]="region"></app-tile>
    </div>


    <div class="control-panel">
        <div class="control-panel__button-container">
            <!-- <button id="forwardOneYear" class="control-panel__btn" (click)="forwardYears(1)">Forward One Year</button>
            <button id="forwardTenYear" class="control-panel__btn" (click)="forwardYears(10)">Forward Ten Years</button>
            <button id="forwardThousandYear" class="control-panel__btn" (click)="forwardYears(1000)">Forward One Thousand Years</button> -->

            <button class="control-panel__btn" (click)="reset()">Reset</button>

            <div class="control-panel__forward-button-container">
                <button class="control-panel__btn" (click)="play(yearsPerSecond.value)"><i class="icon fa fa-play"
                        aria-hidden="true"></i></button>
                <input #yearsPerSecond class="control-panel__years-per-second-input" type="number" id="yearsPerSecond"
                    value=10 min="1" max="100">
                <div class="control-panel__forward-label">years per second</div>
            </div>
            <div class="control-panel__forward-button-container">
                <button id="forwardHundredYear" class="control-panel__btn" (click)="forwardYears(yearsPerStep.value)"><i
                        class="icon fa fa-plus" aria-hidden="true"></i></button>
                <input #yearsPerStep class="control-panel__years-per-second-input" type="number" id="yearsPerStep"
                    value=100 min="1" max="1000">
                <div class="control-panel__forward-label">years forward</div>
            </div>
            <button class="control-panel__btn" (click)="pause()"><i class="icon fa fa-pause"
                    aria-hidden="true"></i></button>

        </div>

    </div>
    <div class="data-container">
        <div class="data-container__data-point">Year: {{year}}</div>
        <div class="data-container__data-point">Population: {{globalPopulation()}}</div>
        <div class="data-container__data-point">Food Yield: {{globalFoodYielded()}}</div>
    </div>


    <!-- <i class="fa fa-male" aria-hidden="true"></i>
    <i class="fa fa-home" aria-hidden="true"></i>
    <i class="fa fa-tree" aria-hidden="true"></i> -->

</div>

// src/components/MiniMap.tsx
import { useRef, useState, useEffect } from 'react';
import { Region } from '../lib/region';
import { Polity } from '../lib/polity';
import { NoPolity } from '../lib/noPolity';
import { Band } from '../lib/band';
import { River } from '../lib/river';
import Tile from './Tile';

interface MiniMapProps {
  title: string;
  createRegions: () => Region[];
  rivers: River[];
}

export default function MiniMap({ title, createRegions, rivers }: MiniMapProps) {
  const regionsRef = useRef<Region[]>([]);
  const politiesRef = useRef<Polity[]>([]);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const [year, setYear] = useState(0);
  const [, forceUpdate] = useState(0);

  function initGame(regions: Region[]) {
    // Add starting polity
    const startingBand = new Band(regions[65], 'Origin', 10, true);
    regions[65]._polity = startingBand;
    politiesRef.current = [startingBand];

    // Apply rivers
    rivers.forEach(river => {
      const riverLines = river.riverDrawing();
      const riverYields = river.tileYields();
      regions.forEach(region => {
        const key = `${region._col}-${region._row}`;
        if (riverLines[key] !== undefined) {
          for (let i = 0; i < riverLines[key].length; i++) {
            region._borders[i] = riverLines[key][i];
          }
        }
        if (riverYields[key] !== undefined) {
          region._riverConnections += riverYields[key];
        }
      });
    });
  }

  function reset() {
    if (intervalRef.current) clearInterval(intervalRef.current);
    intervalRef.current = null;
    const regions = createRegions();
    regionsRef.current = regions;
    initGame(regions);
    setYear(0);
    forceUpdate(n => n + 1);
  }

  useEffect(() => {
    reset();
    return () => {
      if (intervalRef.current) clearInterval(intervalRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function forwardYears(number: number) {
    const regions = regionsRef.current;
    const polities = politiesRef.current;

    for (let i = 0; i < number; i++) {
      // Polities act
      polities.forEach(polity => polity.act(regions));

      // Regions act: add new polities to main array and replenish food
      regions.forEach(region => {
        if (!region._polity._partOfMainArray && region._polity.polityType !== 'None') {
          polities.push(region._polity);
          region._polity._partOfMainArray = true;
        }
        region.replenishFood();
      });

      // Remove dead polities
      for (let j = polities.length - 1; j >= 0; j--) {
        const polity = polities[j];
        if (polity._population <= 1 && polity.polityType !== 'None') {
          polity._region._polity = new NoPolity();
          polities.splice(j, 1);
        }
      }
    }

    setYear(y => y + number);
    forceUpdate(n => n + 1);
  }

  function play(yearsPerSecond: number) {
    pause();
    intervalRef.current = setInterval(() => {
      forwardYears(yearsPerSecond);
    }, 1000);
  }

  function pause() {
    if (intervalRef.current) {
      clearInterval(intervalRef.current);
      intervalRef.current = null;
    }
  }

  function globalPopulation() {
    return politiesRef.current.reduce((sum, p) => sum + p._population, 0);
  }

  function globalFoodYielded() {
    return regionsRef.current.reduce((sum, r) => sum + r._foodYield, 0);
  }

  return (
    <div className="map-container">
      <div className="title-data-container">
        <div className="map-title">{title}</div>
      </div>

      <div className="tile-container">
        {regionsRef.current.map((region, i) => (
          <Tile key={i} region={region} />
        ))}
      </div>

      <div className="control-panel">
        <div className="control-panel__button-container">
          <button className="control-panel__btn" onClick={reset}>Reset</button>

          <div className="control-panel__forward-button-container">
            <button
              className="control-panel__btn"
              onClick={() => {
                const input = document.getElementById(`yps-${title}`) as HTMLInputElement;
                play(parseInt(input?.value ?? '10'));
              }}
            >
              <i className="icon fa fa-play" aria-hidden="true"></i>
            </button>
            <input
              id={`yps-${title}`}
              className="control-panel__years-per-second-input"
              type="number"
              defaultValue={10}
              min={1}
              max={100}
            />
            <div className="control-panel__forward-label">years per second</div>
          </div>

          <div className="control-panel__forward-button-container">
            <button
              className="control-panel__btn"
              onClick={() => {
                const input = document.getElementById(`ypstep-${title}`) as HTMLInputElement;
                forwardYears(parseInt(input?.value ?? '100'));
              }}
            >
              <i className="icon fa fa-plus" aria-hidden="true"></i>
            </button>
            <input
              id={`ypstep-${title}`}
              className="control-panel__years-per-second-input"
              type="number"
              defaultValue={100}
              min={1}
              max={1000}
            />
            <div className="control-panel__forward-label">years forward</div>
          </div>

          <button className="control-panel__btn" onClick={pause}>
            <i className="icon fa fa-pause" aria-hidden="true"></i>
          </button>
        </div>
      </div>

      <div className="data-container">
        <div className="data-container__data-point">Year: {year}</div>
        <div className="data-container__data-point">Population: {globalPopulation()}</div>
        <div className="data-container__data-point">Food Yield: {globalFoodYielded()}</div>
      </div>
    </div>
  );
}
